### ISSUE TITLE
Register object store issue

### ISSUE THREAD

**Issue by yaroslavambrozyak** [datafusion-contrib/datafusion-objectstore-s3#27]
Hi, I`d like to register s3 object store to read files hosted on s3, followed the example I found [here] (https://github.com/datafusion-contrib/datafusion-objectstore-s3/issues/15)

Here is my code part, but it throws me `the trait 'ObjectStore' is not implemented for 'AmazonS3FileSystem'`
```rust
let mut execution_ctx = ExecutionContext::new();
  execution_ctx.register_object_store(
        "s3",
        Arc::new(AmazonS3FileSystem::new(None, None, None, None, None, None).await)
    );
```
how can I fix this? Thanks

**Comment by matthewmturner** [comment]
@yaroslavambrozyak thanks for raising this.

I believe this is likely due to having different versions of the datafusion crate.

Right now, while we are in development mode and still working on 0.1 release, we have pinned to a specific datafusion commit which you will see in our `Cargo.toml`.  You will have to ensure you are using the same datafusion commit in your `Cargo.toml`.  You will also need to ensure any other overlapping dependencies are on the same version.

We are currently planning the 0.1 release at which point we will switch to a specific version of datafusion, likely 7.0.

Hope this helps and thanks for trying this out!

**Comment by seddonm1** [comment]
@yaroslavambrozyak I have imported like this in the meantime:

```
datafusion-objectstore-s3 = { git = "https://github.com/datafusion-contrib/datafusion-objectstore-s3", rev = "366bb6cf51518bc1e3f71ba73f0aff13d6415711" }
```

**Comment by matthewmturner** [comment]
@yaroslavambrozyak closing this issue.  Let us know if any further questions or issues :)

**Comment by yaroslavambrozyak** [comment]
> @yaroslavambrozyak I have imported like this in the meantime:
> 
> ```
> datafusion-objectstore-s3 = { git = "https://github.com/datafusion-contrib/datafusion-objectstore-s3", rev = "366bb6cf51518bc1e3f71ba73f0aff13d6415711" }
> ```

This helped me, thanks guys
